import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Carousel from '@/components/Carousel/carousel'
import Destaque from '@/components/Destaque/Destaque'



export default function Home() {
  return (
    <>
      <Head>
        <title>Loja de Jogos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Carousel/>
        <Destaque/>
      </main>
    </>
  )
}
